name: roadflow_city
description: Top-down traffic and city simulation game (Flutter + Flame).
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.21.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
